secret_key_base: 370b0489e18f85d4908415b8a7f0479e5996c7432bbf27c2fc82df8dbee70aab7389c165b3ba61f7af8c24c0877572ed90bdd88284fd12415c2ba072f3c03ffd
telegram:
  bots:
    reminder:
      token: 6873736492:AAFzurnuY2RKjCYSymvl5ReUYi6TF-OGAWI
      username: ai_reminder_dev_bot
sber:
  auth_url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
  recognize_url: https://smartspeech.sber.ru/rest/v1/speech:recognize
  recognize_token: OTM3YjQ5MWItM2Q0MC00MmM2LThiMmQtODMzYmZlYTBhMDhiOjBkNjQ2NmQ0LWFjNDQtNDNlNC1iZGU4LTZlY2MxYzAyNTliOQ==
  chat_url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
  chat_token: NzMyNGY0MzgtNzFlYS00YjIzLWJmNjEtMTU0MmQxNjc5OTc1OmY1ZjFjZmIzLWU4M2UtNGIwYy1iZjQ5LTFkZGU0MWQ3MGU1Mg==
